Update index.html
Xyoyu/xignotics-vocabulary-directory pull request #2
Opened 2021-03-10 03:21 UTC by Rxspxct

2021-03-11 04:45 UTC, Hopefuls approved these changes
LGTM lol

2021-03-11 04:59 UTC, Hopefuls requested changes

2021-03-11 04:59 UTC, Hopefuls commented on index.html
> + <h5>nani</h5>
Actually, have it uppercase, looks better (`Nani`)

2021-03-17 03:38 UTC, Xyoyu requested changes
Make it propercase pls

2021-03-17 13:02 UTC, Hvskyy commented
changed it

2021-03-29 04:16 UTC, Xyoyu approved these changes

2021-07-08 20:55 UTC, closed without merging